title: "SoofsFiloSophie"
email: sophie.pullens.04@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "favicon.svg"
author: Sophie Pullens
paginate: 30
disqus: "Soofs FiloSophieën over het alledaagse leven."
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sophie:
    name: Sophie Pullens
    display_name: Soof
    avatar: "favicon.svg"
    email: sophie.pullens.04@gmail.com
    web: https://soofsfilosophie.github.io/
    twitter:
    description: "Schrijfster, communicatie specialist, bakkersmeisje"

# Social
social:
  instagram:
  facebook:
  twitter:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
